// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utsvfbnoxvoxbmnkkavd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0c3ZmYm5veHZveGJtbmtrYXZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ5NDk4MzAsImV4cCI6MjA5MDUyNTgzMH0.-PyxlGH1tkM0rwq7Q0qbqOB8vJ6NRPPbC5fSZLgc4UU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});